collarText = choose(
	"THIS PLACE IS A MESSAGE AND PART OF A SYSTEM OF MESSAGES.",
	"PAY ATTENTION TO IT!",
	"SENDING THIS MESSAGE WAS IMPORTANT TO US.",
	"WE CONSIDERED OURSELVES TO BE A POWERFUL CULTURE.",
	"THIS PLACE IS NOT A PLACE OF HONOR.",
	"NO HIGHLY ESTEEMED DEED IS COMMEMORATED HERE.",
	"NOTHING VALUED IS HERE.",
	"WHAT IS HERE WAS DANGEROUS AND REPULSIVE TO US.",
	"THIS MESSAGE IS A WARNING ABOUT DANGER.",
	"THE DANGER IS IN A PARTICULAR LOCATION. IT INCREASES TOWARDS A CENTER.",
	"THE CENTER OF DANGER IS HERE.",
	"THE DANGER IS OF A PARTICULAR SIZE AND SHAPE, AND BELOW US.",
	"THE DANGER IS STILL PRESENT IN YOUR TIME AS IT WAS IN OURS.",
	"THE DANGER IS TO THE BODY, AND IT CAN KILL.",
	"THE FORM OF THE DANGER IS AN EMANATION OF ENERGY.",
	"THIS PLACE IS BEST LEFT SHUNNED AND LEFT UNINHABITED."

)

return collarText;